<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;Win32</Platforms>
    <RootNamespace>ViewCs</RootNamespace>
    <TargetFrameworks>
      net48;
    </TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
    <ProjectReference Include="..\WinFormsControl\WinFormsControl.NetOld.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Form1.Designer.cs" />
    <Compile Include="Form1.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

</Project>
