<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <MyType>WindowsForms</MyType>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;Win32</Platforms>
    <RootNamespace>ViewVb</RootNamespace>
    <StartupObject>ViewVb.My.MyApplication</StartupObject>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsControl\WinFormsControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ApplicationEvents.vb" />
    <Compile Include="Form1.Designer.vb" />
    <Compile Include="Form1.vb" />
    <Compile Include="My Project\Application.Designer.vb" />
  </ItemGroup>

</Project>
